spring:
  datasource:
    druid:
      username: root
      password: password
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/crud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
beetlsql.basePackage: com.yunnuy.crud.dao
beetl.suffix: html
beetl-beetlsql.dev: true
